### ISSUE TITLE
strike slip rate drastic changes in Mod.patch file

### ISSUE THREAD

**Issue by jjeeffff** [jploveless/Blocks#10]
Dear members,
  I used the Blocks for an interseismic coupling inversion of a strike slip fault. The result of strike slip rate from relative block motion in Mod.patch file is shown in figure below. It is noteworthy that certain fault segments exhibit positive slip rates while others display negative values.  I found that this variation in sign is related to the south-dipping or north-dipping of faults. However, the definition of left lateral or right lateral strike slip should be independent of the fault dip. So I'm confused about such reversal of strike slip direction. 
![strike-slip](https://github.com/jploveless/Blocks/assets/55947426/dcf4ad74-01bd-470a-9646-81e32c96d0a4)
  Another question is about the dip slip rate from relative block motion in Mod.patch file. The inversion result of dip slip is unrealistically large, especially in the element whose dip angle is close to 90°. Is there any method to constrain the dip slip rate in the patch inversion?

Thanks,
Jeff
![dip-slip](https://github.com/jploveless/Blocks/assets/55947426/00fe1299-13c4-4807-b30c-2f97abcb7143)

**Comment by jploveless** [comment]
Hi Jeff, 

Thank you for posting about this issue. There are a few potential explanations for the abrupt variation in slip rate. First, if there are block boundaries that serve to segment the mesh (i.e. at triple junctions), the relative block motion will necessarily vary. This may be the case for your model, but I can't tell without seeing the full model geometry. The second explanation is a likely bug in the projection of relative block motion onto the triangular elements. In the current version of the code, we use the segment nearest each element to determine which blocks lie to the east and west of that element. When there are variations in element dip, particularly around nearly vertical faults, there can be discrepancies in which block is considered to lie east vs. west. We have rarely used strike-slip faults as triangulated surfaces, and I've incompletely tested the projection routine on such faults. I am actively working on a few subroutines that will rely more heavily on having correct signs for the relative block motion, and so hopefully it won't be too long before I can upload a new version of the code that correctly calculates the sign of slip. 

Regarding dip-slip, for very steeply dipping triangular elements, we suggest not considering the dip-slip rates but rather the tensile (element normal) slip rates. Meade and Hager (2005) and Meade and Loveless (2009) discuss this in more detail. For every fault, we calculate strike-slip and one of the two strike-perpendicular components of slip. For dipping faults, we calculate dip-slip, and for vertical faults, we calculate tensile-slip. Again, the slip rates from relative block motion are a less frequently used result, but hopefully we can make this part of the code more reliable soon. 

If you are willing, could you share your output directory with me that shows these results? That way, I could try to make sure that the new edits to the routine allow for correct calculation of your slip rates. You can feel free to contact me via email (jloveles@smith.edu)

**Comment by jjeeffff** [comment]
Dear Dr. Loveless,

Thanks a lot for your kind help. I try to send you the output directory via email, but it keeps failing. So I'm attaching the file here instead.
[0000000038.zip](https://github.com/jploveless/Blocks/files/14458593/0000000038.zip)

**Comment by jploveless** [comment]
Should be fixed in https://github.com/jploveless/Blocks/commit/f4471e864f1589146d358ad292c848439ebbc0e0
