### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by HXPsunset** [jploveless/Blocks#4]
Hello,

When I was trying to learn from the examples you gave, the function “StartsWith ” seems to be missing. Is there a problem with my use? I don't know what happened. And I can't find this function in all the files. Please tell me what should I do.

Thanks,
sunset

**Comment by jploveless** [comment]
startsWith.m is a built-in function introduced in Matlab R2016b. You should be able to replace references to startsWith with strmatch and the behavior should be the same. The Mathworks now recommends use of startsWith.
