### ISSUE TITLE
Intra_plate

### ISSUE THREAD

**Issue by suribabud** [jploveless/Blocks#6]
Hi,
First of all thank you so much for keeping this wonderful software in open-source. I have doubt regarding intraplate slip rate estimation using GPS network. Is it possible, if it is please kindly provide some suggestions to calculate the slip rate in intraplate regions using your software.

**Comment by brendanjmeade** [comment]
Blocks is most commonly used at plate boundary settings.  Whether or not it's an appropriate choice for particular intraplate settings is something that individual researchers may determine on a case-by-case basis.

**Comment by suribabud** [comment]
Thank you Meade, In my study area Kachchh, India, we have around 5 faults within the 220 km^2 area. This particular area is covered with around 27 GPS stations running from the last 12 years (17 permanent+ remaining campaigns). Using this continuous data set I want to calculate the slip rate.

Please suggest if there any limitations are present in Blocks software to calculate the slip rate in the intraplate.

**Comment by brendanjmeade** [comment]
There's no definitive answer but rather that's something that you can determine.  Best of luck!

**Comment by suribabud** [comment]
Thank you so much. I will try and update you.
