### ISSUE TITLE
Error while running the blocks in Matlab

### ISSUE THREAD

**Issue by suribabud** [jploveless/Blocks#7]
While running the sample file in Block software, I'm getting below error. Please check it once.

>> Blocks('/home/rakesh/Documents/Blocks-master/Kachchh1/command')
Parsing input data...Error using fgets
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in fgetl (line 32)
[tline,lt] = fgets(fid);

Error in ReadCommand (line 57)
   line                                               = fgetl(infile);

Error in Blocks (line 5)
Command                                          = ReadCommand(commandFile); % Read command file

**Comment by jploveless** [comment]
Please see the Blocks wiki for information about structuring the command file, specifically [the inputs page](https://github.com/jploveless/Blocks/wiki/Input-overview). 

I would recommend looking through the example Japan model, including its command file and geometry files.

**Comment by suribabud** [comment]
Thank you so much. It is running now
I used simpleexample files for test run.
