### ISSUE TITLE
How to use InSAR data in Blocks

### ISSUE THREAD

**Issue by suribabud** [jploveless/Blocks#8]
I processed around 150 SLC images for estimating the crustal deformation (only descending orbit available) using PS-InSAR technique. How to give this input to Blocks?

**Comment by jploveless** [comment]
Yes, please see the information in `help ReadSar` for details about formatting a SAR data file. Please also see the [wiki entry about the command file](https://github.com/jploveless/Blocks/wiki/Input-overview#command-file-options) for information about specifying the name of the SAR data file.

**Comment by suribabud** [comment]
Thank you.

**Comment by rishabhdutta** [comment]
I was also checking the InSAR capabilities in Blocks. I wonder if multiple InSAR datasets with different sets of look angles could be accommodated? How does the command file change? Thanks in advance.

**Comment by jploveless** [comment]
Currently Blocks supports only one SAR dataset, with a single look vector.
