### ISSUE TITLE
Block modeling for Intraplate

### ISSUE THREAD

**Issue by suribabud** [jploveless/Blocks#9]
Dear members,
I already mentioned that I'm working on Intraplate region. I want to separate the Intraplate region to two different blocks because of GPS velocities (Northward stations showing southward motion and vise versa; attached figure). Then based on GPS velocities I wanna calculate the two different Euler poles for two blocks. Is it correct procedure to calculate the slip rate of different faults presented in two different blocks?

Your kind suggestions will enhance my knowledge.
![123](https://github.com/jploveless/Blocks/assets/81164105/bb78b6df-225b-4bc2-b0c0-a18f5b87d47d)

(Dumka et al., 2023;   GPS and InSAR derived evidences of intra‐basin stress and strike‐slip tectonics in the vicinity of 2001 (M7.7) earthquake, Kachchh, western India)

**Comment by jploveless** [comment]
Changes in patterns of GPS velocities may signal an active block boundary between groups of stations, so you may wish to separate these groups of stations into two blocks as suspected. If you haven't yet done so, please read [Meade and Loveless (2009)](https://dx.doi.org/10.1785/0120090088) for a theoretical background in block modeling.

**Comment by suribabud** [comment]
Thank you
